[build]
  command = "CI= npm run build"
  publish = "build"

[[redirects]]
  from = "/api/*"
  to = "${REACT_APP_API_URL}/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

